from .user_schema import UserSchema
from .role_schema import RoleSchema
from .learning_path_schema import LearningPathSchema
from .module_schema import ModuleSchema
from .resource_schema import ResourceSchema
from .quiz_schema import QuizSchema
from .comment_schema import CommentSchema
from .rating_schema import RatingSchema
from .badge_schema import BadgeSchema
from .achievement_schema import AchievementSchema
from .progress_schema import ProgressSchema
