"""Add Africa's Talking models and user phone number

Revision ID: 8e3f66fa227b
Revises: 5b98ecdd26b5
Create Date: 2025-09-21 15:14:25.855799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3f66fa227b'
down_revision = '5b98ecdd26b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_users_phone_number', ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_phone_number', type_='unique')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
