"""Add status column to User model

Revision ID: be4d3f7098eb
Revises: 8e3f66fa227b
Create Date: 2025-09-24 19:26:47.180244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4d3f7098eb'
down_revision = '8e3f66fa227b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='active'))
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
